name: factodoctor
description: Doctor Telemedicine App for FactoHR
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'  # ← CHANGE THIS LINE
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # ✅ Firebase (Compatible Versions)
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.7.4
  firebase_storage: ^11.6.4
  
  # ✅ Agora & Permissions
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.2.0
  
  # ✅ Notifications
  flutter_local_notifications: ^17.1.0
  
  # ✅ State Management
  provider: ^6.1.2
  
  # ✅ NEW LINE for Firebase Functions:
  cloud_functions: ^4.6.4
  
  # ✅ UI & Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add your assets if needed
  # assets:
  #   - assets/images/
  #   - assets/icons/